In [2]:
print("hello")

hello

In [5]:
#pip install yfinance

In [3]:
import sys
!{sys.executable} -m pip install yfinance

Collecting yfinance
  Using cached yfinance-1.3.0-py2.py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from yfinance) (3.0.0)
Requirement already satisfied: numpy>=1.16.5 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: requests>=2.31 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from yfinance) (2.32.5)
Collecting multitasking>=0.0.7 (from yfinance)
  Using cached multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: platformdirs>=2.0.0 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from yfinance) (4.5.1)
Collecting pytz>=2022.5 (from yfinance)
  Downloading pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.4.7-py3-none-any.whl.metadata (23 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.0.6-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from yfinance) (4.14.3)
Collecting curl_cffi>=0.15 (from yfinance)
  Using cached curl_cffi-0.15.0-cp310-abi3-win_amd64.whl.metadata (18 kB)
Collecting protobuf>=3.19.0 (from yfinance)
  Downloading protobuf-7.35.0-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: websockets>=13.0 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.1.4)
Requirement already satisfied: rich in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: pycparser in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests>=2.31->yfinance) (2.6.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\Users\v\AppData\Local\Programs\Python\Python314\Lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Using cached yfinance-1.3.0-py2.py3-none-any.whl (133 kB)
Using cached curl_cffi-0.15.0-cp310-abi3-win_amd64.whl (1.7 MB)
Downloading frozendict-2.4.7-py3-none-any.whl (16 kB)
Using cached multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.0.6-py3-none-any.whl (146 kB)
Downloading protobuf-7.35.0-cp310-abi3-win_amd64.whl (439 kB)
Downloading pytz-2026.2-py2.py3-none-any.whl (510 kB)
Installing collected packages: pytz, peewee, multitasking, protobuf, frozendict, curl_cffi, yfinance

   ---------------------------------------- 0/7 [pytz]
   ---------------------------------------- 0/7 [pytz]
   ---------------------------------------- 0/7 [pytz]
   ----- ---------------------------------- 1/7 [peewee]
   ----------------- ---------------------- 3/7 [protobuf]
   ---------------------- ----------------- 4/7 [frozendict]
   ---------------------------- ----------- 5/7 [curl_cffi]
   ---------------------------------- ----- 6/7 [yfinance]
   ---------------------------------------- 7/7 [yfinance]

Successfully installed curl_cffi-0.15.0 frozendict-2.4.7 multitasking-0.0.13 peewee-4.0.6 protobuf-7.35.0 pytz-2026.2 yfinance-1.3.0

  WARNING: The script pwiz.exe is installed in 'c:\Users\v\AppData\Local\Programs\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script curl-cffi.exe is installed in 'c:\Users\v\AppData\Local\Programs\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script sample.exe is installed in 'c:\Users\v\AppData\Local\Programs\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import yfinance as yf

In [5]:
from datetime import datetime
end = datetime.now()
start = datetime(end.year - 20 , end.month, end.day)

In [6]:
stock = "GOOG"
google_data = yf.download(stock,start,end)

[*********************100%***********************]  1 of 1 completed

In [7]:
google_data.head()

Price          Close      High       Low      Open     Volume
Ticker          GOOG      GOOG      GOOG      GOOG       GOOG
Date
2006-05-22  9.163884  9.215268  9.023072  9.087302  345466056
2006-05-23  9.278262  9.483304  9.228361  9.244418  360666820
2006-05-24  9.418334  9.472435  9.180189  9.321989  383584400
2006-05-25  9.461319  9.461566  9.197482  9.364728  329012615
2006-05-26  9.420805  9.532714  9.388196  9.499857  147229793

In [8]:
google_data.shape

(5031, 5)

In [9]:
google_data.describe()

Price         Close         High          Low         Open        Volume
Ticker         GOOG         GOOG         GOOG         GOOG          GOOG
count   5031.000000  5031.000000  5031.000000  5031.000000  5.031000e+03
mean      64.601530    65.271785    63.883743    64.556829  7.947194e+07
std       68.753567    69.501644    67.893261    68.661624  8.792527e+07
min        6.359753     6.654470     6.109256     6.485001  1.584340e+05
25%       14.723234    14.843294    14.625036    14.734845  2.460200e+07
50%       36.757725    36.968985    36.502817    36.756235  3.927200e+07
75%       96.348976    98.307410    94.917986    96.398563  1.026400e+08
max      399.040009   404.470001   393.670013   397.059998  9.349835e+08

In [10]:
google_data.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 5031 entries, 2006-05-22 to 2026-05-20
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, GOOG)   5031 non-null   float64
 1   (High, GOOG)    5031 non-null   float64
 2   (Low, GOOG)     5031 non-null   float64
 3   (Open, GOOG)    5031 non-null   float64
 4   (Volume, GOOG)  5031 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 235.8 KB

In [11]:
google_data.isna().sum()

Price   Ticker
Close   GOOG      0
High    GOOG      0
Low     GOOG      0
Open    GOOG      0
Volume  GOOG      0
dtype: int64

In [12]:
import matplotlib.pyplot as plt
%matplotlib inline